#!/bin/bash

set -euxo pipefail

up () { docker compose up --timeout 300 --wait; }
down () { docker compose down --timeout 300; }

for CMD in $@; do
	case $CMD in
		up ) up;;
		down ) down;;
		* ) exit 1;;
	esac
done
