#!/bin/bash

set -euxo pipefail

PROJECT_DIRECTORY=$(realpath $(dirname $BASH_SOURCE))

docker compose --project-name "nextcloud" --project-directory $PROJECT_DIRECTORY up --timeout 300 --wait --detach "$@"
